clc;
clear;

%% 1. Single Generation of the Problem Instance

number_of_activity = 16;
number_of_pactivity = 7;
number_of_worker = 40;
number_of_skill = 10;
workers = number_of_worker;

skill_set = 1:number_of_skill;
activity_set = 1:number_of_activity;
worker_set = 1:number_of_worker;

while(1)
    cp1 = randi(number_of_activity-1);
    cp2 = cp1 + number_of_pactivity;

    if cp2 <= number_of_activity-1
        break
    end
end

pactivity_set = activity_set(1,cp1+1:cp2);

[skill_matrix, total_skill_number] = ...
    number_of_skills_and_workers( ...
    number_of_activity, ...
    number_of_skill, ...
    number_of_worker);

[single_skill_set_of_worker, ...
 single_HM_proficiency_level, ...
 single_HT_proficiency_level, ...
 single_HM_worker_cost, ...
 single_HT_worker_cost] = ...
    single_skill_matrix( ...
    number_of_worker, ...
    number_of_skill, ...
    total_skill_number);

[multi_skill_set_of_worker, ...
 multi_HM_proficiency_level, ...
 multi_HT_proficiency_level, ...
 multi_HM_worker_cost, ...
 multi_HT_worker_cost] = ...
    multi_skill_matrix( ...
    number_of_worker, ...
    number_of_skill, ...
    total_skill_number);

task_time_of_each_skill = ...
    task_times( ...
    number_of_activity, ...
    skill_matrix, ...
    number_of_skill);

predecessor_matrix = ...
    predecence_relationship( ...
    number_of_activity, ...
    pactivity_set);

successor_matrix = ...
    successor_relationship( ...
    number_of_activity, ...
    predecessor_matrix);

[swc_single, swc_multi] = ...
    waiting( ...
    number_of_activity, ...
    predecessor_matrix);


%% 2. SABİT NSGA-II PARAMETRELERİ

run_number = 30;
number_of_algorithm = 4;

population_size = 150;
crprob = 0.7;
mutprob = 0.10;
iteration_number = 750;


%% 3. Preallocation of the result matrices

time = zeros(run_number, number_of_algorithm);

Cmetric   = zeros(run_number, 12);
Dmetric   = zeros(run_number, 4);
OSmetric  = zeros(run_number, 6);
Npsmetric = zeros(run_number, 4);
Nndmetric = zeros(run_number, 4);
Igdmetric = zeros(run_number, 4);
Spmetric  = zeros(run_number, 4);
MIDmetric = zeros(run_number, 4);
SNSmetric = zeros(run_number, 4);

tut_activity_pop = cell(run_number, number_of_algorithm);
tut_worker_pop   = cell(run_number, number_of_algorithm);

for b = 1:run_number

    rng(b,'twister');

        %% A1

    tic;
    [activity_pop, worker_pop, pobje, managerial_cost_S1] = ...
        NSGA_II_S1_SS(population_size,...
                      number_of_activity,...
                      single_skill_set_of_worker,...
                      single_HT_proficiency_level,...
                      task_time_of_each_skill,...
                      skill_matrix,...
                      total_skill_number,...
                      predecessor_matrix,...
                      iteration_number,...
                      successor_matrix,...
                      crprob,...
                      mutprob,...
                      number_of_skill,...
                      number_of_worker,...
                      single_HT_worker_cost,...
                      swc_single);

    pobje1 = pobje;

    time(b,1)=toc;

    %% A2

    tic;
    [activity_pop, worker_pop, pobje, managerial_cost_S2] = ...
        NSGA_II_S2_SS(population_size,...
                      number_of_activity,...
                      single_skill_set_of_worker,...
                      single_HT_proficiency_level,...
                      task_time_of_each_skill,...
                      skill_matrix,...
                      total_skill_number,...
                      predecessor_matrix,...
                      iteration_number,...
                      successor_matrix,...
                      crprob,...
                      mutprob,...
                      number_of_skill,...
                      number_of_worker,...
                      single_HT_worker_cost,...
                      swc_single);

    pobje2=pobje;

    time(b,2)=toc;

    %% A3

    tic;
    [activity_pop, worker_pop, pobje, managerial_cost_S3] = ...
        NSGA_II_S3_MS(population_size,...
                      number_of_activity,...
                      multi_skill_set_of_worker,...
                      multi_HT_proficiency_level,...
                      task_time_of_each_skill,...
                      skill_matrix,...
                      total_skill_number,...
                      predecessor_matrix,...
                      iteration_number,...
                      successor_matrix,...
                      crprob,...
                      mutprob,...
                      number_of_skill,...
                      number_of_worker,...
                      multi_HT_worker_cost,...
                      swc_multi);

    pobje3=pobje;

    time(b,3)=toc;

    %% A4

    tic;
    [activity_pop, worker_pop, pobje, managerial_cost_S4] = ...
        NSGA_II_S4_MS(population_size,...
                      number_of_activity,...
                      multi_skill_set_of_worker,...
                      multi_HT_proficiency_level,...
                      task_time_of_each_skill,...
                      skill_matrix,...
                      total_skill_number,...
                      predecessor_matrix,...
                      iteration_number,...
                      successor_matrix,...
                      crprob,...
                      mutprob,...
                      number_of_skill,...
                      number_of_worker,...
                      multi_HT_worker_cost,...
                      swc_multi);

    pobje4=pobje;

    time(b,4)=toc;

    %% Performance metrics

    [d1,d2,d3,d4,d5,d6,d7,d8,d9,d10,d11,d12,...
     drr1,drr2,drr3,drr4,...
     OS12,OS13,OS14,OS23,OS24,OS34,...
     Nnd1,Nnd2,Nnd3,Nnd4,...
     Nps1,Nps2,Nps3,Nps4,...
     Igd1,Igd2,Igd3,Igd4,...
     Sp1,Sp2,Sp3,Sp4,mids,sns] = ...
     metrics(pobje1,pobje2,pobje3,pobje4);

    Cmetric(b,:)   = [d1 d2 d3 d4 d5 d6 d7 d8 d9 d10 d11 d12];
    Dmetric(b,:)   = [drr1 drr2 drr3 drr4];
    OSmetric(b,:)  = [OS12 OS13 OS14 OS23 OS24 OS34];
    Npsmetric(b,:) = [Nps1 Nps2 Nps3 Nps4];
    Nndmetric(b,:) = [Nnd1 Nnd2 Nnd3 Nnd4];
    Igdmetric(b,:) = [Igd1 Igd2 Igd3 Igd4];
    Spmetric(b,:)  = [Sp1 Sp2 Sp3 Sp4];
    MIDmetric(b,:) = mids;
    SNSmetric(b,:) = sns;

end

%% ============================================================
% RANDOM SEED STABILITY ANALYSIS
% Mean, standard deviation and coefficient of variation (CV)
% for IGD, MID, SNS and SP
%% ============================================================

algorithm_names = {'A1'; 'A2'; 'A3'; 'A4'};

% Mean values
mean_IGD = mean(Igdmetric, 1, 'omitnan')';
mean_MID = mean(MIDmetric, 1, 'omitnan')';
mean_SNS = mean(SNSmetric, 1, 'omitnan')';
mean_SP  = mean(Spmetric, 1, 'omitnan')';

% Standard deviation
std_IGD = std(Igdmetric, 0, 1, 'omitnan')';
std_MID = std(MIDmetric, 0, 1, 'omitnan')';
std_SNS = std(SNSmetric, 0, 1, 'omitnan')';
std_SP  = std(Spmetric, 0, 1, 'omitnan')';

% Coefficient of Variation: CV (%) = std / mean * 100
cv_IGD = 100 .* std_IGD ./ abs(mean_IGD);
cv_MID = 100 .* std_MID ./ abs(mean_MID);
cv_SNS = 100 .* std_SNS ./ abs(mean_SNS);
cv_SP  = 100 .* std_SP  ./ abs(mean_SP);

% Removing Inf and NaN values caused by zero average
cv_IGD(~isfinite(cv_IGD)) = NaN;
cv_MID(~isfinite(cv_MID)) = NaN;
cv_SNS(~isfinite(cv_SNS)) = NaN;
cv_SP(~isfinite(cv_SP))   = NaN;

%% Summary table

stability_summary = table( ...
    algorithm_names, ...
    mean_IGD, std_IGD, cv_IGD, ...
    mean_MID, std_MID, cv_MID, ...
    mean_SNS, std_SNS, cv_SNS, ...
    mean_SP,  std_SP,  cv_SP, ...
    'VariableNames', { ...
    'Algorithm', ...
    'IGD_Mean', 'IGD_Std', 'IGD_CV_Percent', ...
    'MID_Mean', 'MID_Std', 'MID_CV_Percent', ...
    'SNS_Mean', 'SNS_Std', 'SNS_CV_Percent', ...
    'SP_Mean',  'SP_Std',  'SP_CV_Percent'});

disp('Random seed stability analysis:');
disp(stability_summary);

%% Results for each seed

seed_numbers = (1:run_number)';

raw_results = table( ...
    seed_numbers, ...
    Igdmetric(:,1), Igdmetric(:,2), Igdmetric(:,3), Igdmetric(:,4), ...
    MIDmetric(:,1), MIDmetric(:,2), MIDmetric(:,3), MIDmetric(:,4), ...
    SNSmetric(:,1), SNSmetric(:,2), SNSmetric(:,3), SNSmetric(:,4), ...
    Spmetric(:,1),  Spmetric(:,2),  Spmetric(:,3),  Spmetric(:,4), ...
    'VariableNames', { ...
    'Seed', ...
    'IGD_A1', 'IGD_A2', 'IGD_A3', 'IGD_A4', ...
    'MID_A1', 'MID_A2', 'MID_A3', 'MID_A4', ...
    'SNS_A1', 'SNS_A2', 'SNS_A3', 'SNS_A4', ...
    'SP_A1',  'SP_A2',  'SP_A3',  'SP_A4'});

%% Optional Runtime Summary

mean_time = mean(time, 1, 'omitnan')';
std_time  = std(time, 0, 1, 'omitnan')';
cv_time   = 100 .* std_time ./ abs(mean_time);

cv_time(~isfinite(cv_time)) = NaN;

time_summary = table( ...
    algorithm_names, mean_time, std_time, cv_time, ...
    'VariableNames', { ...
    'Algorithm', 'Time_Mean', 'Time_Std', 'Time_CV_Percent'});

%% Write the Excel file.

output_filename = 'Random_Seed_Stability_Analysis.xlsx';

writetable(stability_summary, output_filename, ...
    'Sheet', 'Summary');

writetable(raw_results, output_filename, ...
    'Sheet', 'Raw_Metric_Results');

writetable(time_summary, output_filename, ...
    'Sheet', 'CPU_Time');

%% Save as MAT file.

save('Random_Seed_Stability_Analysis.mat', ...
    'Igdmetric', 'MIDmetric', 'SNSmetric', 'Spmetric', ...
    'time', 'stability_summary', 'raw_results', 'time_summary');

fprintf('\nSeed stability results were saved to:\n');
fprintf('%s\n', output_filename);